### ISSUE TITLE
BUG: `include_usage` implementation doesn't seem to work.

### ISSUE THREAD

**Issue by janaka** [openai/openai-dotnet#103]
This feature seems to be switched on to `true` by default in the OpenAI client (correct?). However, the `StreamingChatCompletionUpdate.Usage` property is always `null`. This appears to be a bug. 

Before `CompleteChatStreamingAsync(messages, options)` is called when I inspect the `options` object, `Stream=null` and `StreamOptions.IncludeUsage=true`. However, immediately after `CompleteChatStreamingAsync(messages, options)` is called when I inspect the `options` object, `Stream=true` and `SteamOptions` is `null`. 

Client version: Azure OpenAI
Azure client version: 2.0.0 Beta 2
OpenAI Client version: implicit (>= 2.0.0-beta.5)
OpenAI API version option: `AzureOpenAIClientOptions.ServiceVersion.V2024_06_01`
OpenAI API provider : Azure OpenAI
Model name: GPT-4o

**Comment by joseharriaga** [comment]
Thank you for reaching out, @janaka ! And thank you for all the useful debug information you provided! 

The Azure OpenAI service does not yet support `include_usage` (a.k.a. `stream_options`).

Also, for future reference, this repo corresponds to the OpenAI library. If you're using the Azure.AI.OpenAI library instead and are having trouble with it, you can file issues in the Azure repo here: 🔗 https://github.com/Azure/azure-sdk-for-net. Thank you!

**Comment by janaka** [comment]
@joseharriaga hi, the inference service now have this option? given it's in the specs? 

https://github.com/Azure/azure-rest-api-specs/blob/3c4ddfa53535e9e2b775d885d91aa1ab57a7a7fd/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2024-07-01-preview/inference.json#L267

**Comment by janaka** [comment]
I confirm this works for me now. Tested against eastus and sweden with Postman.

When I checked last week it appears the original issue I reported is still the behaviour. I think it's a bug caused by the constructor of one of the classes missing the param.

@joseharriaga any idea when fixing this might get prioritised?

**Comment by janaka** [comment]
it would be great it somebody can confirm or deny this bug exists. afaik the class hasn't been touched in the last month.

**Comment by janaka** [comment]
@joseharriaga  or somebody working on this project, can you please acknowledge that this and reopen the issue 🙏🏾
