### ISSUE TITLE
Allow multiple granularities in AudioTranscriptionOptions 

### ISSUE THREAD

**Issue by RogerBarreto** [openai/openai-dotnet#104]
As per API definition, the granularities are multiple, but in current design we can only have one or another.

https://platform.openai.com/docs/api-reference/audio/createTranscription#audio-createtranscription-timestamp_granularities

![image](https://github.com/openai/openai-dotnet/assets/19890735/f21a0b4c-0ce9-461f-8d3c-3e0fdfce0c21)

**Comment by joseharriaga** [comment]
Thank you for reaching out, @RogerBarreto ! You can set both options like this:

```csharp
AudioTranscriptionOptions options = new()
{
    ResponseFormat = AudioTranscriptionFormat.Verbose,
    Granularities = AudioTimestampGranularities.Word | AudioTimestampGranularities.Segment,
};
```

**Comment by RogerBarreto** [comment]
That's great, missed that, thanks
