### ISSUE TITLE
Chat Completion Options Can't Set Tools

### ISSUE THREAD

**Issue by JustinFay01** [openai/openai-dotnet#134]
### Goal

I want to use arrays of tools based on user query parameters. 

### Working Implementation

![image](https://github.com/user-attachments/assets/4ef12daf-b293-4de9-8faa-89b51c116354)

### Failing (due to lack of setter)

![image](https://github.com/user-attachments/assets/5bfc386b-d641-4172-9c47-74da4b417750)

![image](https://github.com/user-attachments/assets/c1aadb98-f9bd-4dd3-a7a0-505026608cc6)

**Comment by crickman** [comment]
@JustinFay01  - Use `AddRange()` and drop your usage of `ToList()`

**Comment by JustinFay01** [comment]
> @JustinFay01 - Use `AddRange()` and drop your usage of `ToList()`
> 
> > `Metadata` and other properties have been implemented in a similar fashion.

Thank you so much! Do you know why it was implemented like this?
