### ISSUE TITLE
Initialize ChatClient  with azure open ai key and endpoint values

### ISSUE THREAD

**Issue by asith-w** [openai/openai-dotnet#151]
I have   "AzureOpenAIApiKey",    "AzureOpenAIEndpoint" and azure model . can I initialize ChatClient using those values something like below ?

` ChatClient client = new(model: "gpt-4o",  "AZURE-OPENAI_API_KEY" ,  "AZURE-OPENAI_ENDPOINT". ),);`

**Comment by joseharriaga** [comment]
Thank you for reaching out, @asith-w ! To connect to the Azure OpenAI service, please use the Azure OpenAI library here: 
🔗 https://www.nuget.org/packages/Azure.AI.OpenAI. 

For more information, you can check out the README and samples of the Azure OpenAI library in the `azure-sdk-for-net` repo here:
🔗 https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/openai/Azure.AI.OpenAI/README.md
