### ISSUE TITLE
Add Support for OpenAI new Structured Outputs.

### ISSUE THREAD

**Issue by RogerBarreto** [openai/openai-dotnet#160]
## Add Support for Structured Outputs

As mentioned in the [recent blog post](https://openai.com/index/introducing-structured-outputs-in-the-api/) from OpenAI. 

Now is possible to specify the `response_format` as `json_schema`.

### Additional context

- [X] This is not a feature request for the underlying OpenAI API
- [X] This is not a feature request for Azure OpenAI

**Comment by RogerBarreto** [comment]
Duplication of:

https://github.com/microsoft/semantic-kernel/issues/7946

**Comment by twf-datacom** [comment]
To make it similar to the python and node sdks that use pydantic and zod respectively, could we use something like NJsonSchema to specify the response_format?

**Comment by MosheAzraf** [comment]
I've tried to use it, it does response with a JSON string, but doesn't always response with a consist object form,
In fact, I've opened an issue about that, but I didn't included the response type in my example code..

**Comment by sagos95** [comment]
It would be brilliant if there were the ability to use this feature like as the JsonSerializer works, for example: `var pocoModel = chatCompletionService.GetChatMessageContentsAsync<PocoUserResponseType>("prompt")` or something similar.

**Comment by HavenDV** [comment]
I added this feature to LangChain.NET OpenAI generated SDK today, here's what it looks like, maybe it will help. It also includes trimming/NativeAOT support:
```csharp
using OpenAI;

using var api = new OpenAiApi("API_KEY");

var response = await api.Chat.CreateChatCompletionAsAsync<Weather>(
    messages: ["Generate random weather."],
    model: CreateChatCompletionRequestModel.Gpt4oMini,
    jsonSerializerOptions: new JsonSerializerOptions
    {
        Converters = {new JsonStringEnumConverter()},
    });
// or (if you need trimmable/NativeAOT version)
var response = await api.Chat.CreateChatCompletionAsAsync(
    jsonTypeInfo: SourceGeneratedContext.Default.Weather,
    messages: ["Generate random weather."],
    model: CreateChatCompletionRequestModel.Gpt4oMini);

// response.Value1 contains the structured output
// response.Value2 contains the CreateChatCompletionResponse object
```
```
Weather:
Location: San Francisco, CA
Temperature: 65
Unit: Fahrenheit
Description: Partly cloudy with a light breeze and occasional sunshine.
Raw Response:
{"Location":"San Francisco, CA","Temperature":65,"Unit":"Fahrenheit","Description":"Partly cloudy with a light breeze and occasional sunshine."}
```
Additional code for trimmable/NativeAOT version:
```csharp
[JsonSourceGenerationOptions(Converters = [typeof(JsonStringEnumConverter<Unit>)])]
[JsonSerializable(typeof(Weather))]
public partial class SourceGeneratedContext : JsonSerializerContext;
```

Tests are available here:
https://github.com/tryAGI/OpenAI/blob/main/src/tests/OpenAI.IntegrationTests/Tests.Chat.StructuredOutputs.cs
Main implementation is here:
https://github.com/tryAGI/OpenAI/blob/main/src/libs/OpenAI/TypeToSchemaHelpers.cs

**Comment by StephenHodgson** [comment]
I too have finished Structured Outputs in [OpenAI-DotNet](https://github.com/RageAgainstThePixel/OpenAI-DotNet)

**Comment by sagos95** [comment]
@StephenHodgson works fine! But it can't deserialize `bool?` for some reason. Anyway, thanks for your solution

**Comment by joseharriaga** [comment]
Support for structured outputs has been added as part of this PR: 🔗 https://github.com/openai/openai-dotnet/pull/180

It is now available in version 2.0.0-beta.9: 🔗 https://www.nuget.org/packages/OpenAI/2.0.0-beta.9

**Comment by andreylukin** [comment]
Hi, I dont see a JSON Schema generator implementation as part of 2.0.0-beta.9 or 2.0.0-beta.10. Are there any plans to add it?

**Comment by r-Larch** [comment]
Hi @andreylukin, @sagos95 and @StephenHodgson 

I've written a JSON Schema generator to produce OpenAi compatible JSON Schema. 
It's available as Nuget:

[LarchSys.OpenAi.JsonSchema](https://github.com/r-Larch/OpenAi.JsonSchema)

> LarchSys.OpenAi.JsonSchema is a lightweight library for generating valid JSON Schema for OpenAI models' Structured Outputs feature. It supports a wide range of types, ensures compatibility with OpenAI's JSON Schema format, and leverages C# descriptions and attributes for schema generation.

**Comment by StephenHodgson** [comment]
FWIW, starting in .net 9 System.Text.Json has support to [generate and export schema for you](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.schema.jsonschemaexporter)

- https://github.com/dotnet/runtime/issues/100159
