### ISSUE TITLE
Get the usage when generating embeddings.

### ISSUE THREAD

**Issue by cosmez** [openai/openai-dotnet#166]
### Confirm this is not a feature request for the underlying OpenAI API.

- [X] This is not a feature request for the underlying OpenAI API

### Confirm this is not a feature request for Azure OpenAI.

- [ ] This is not a feature request for Azure OpenAI

### Describe the feature or improvement you're requesting

Token usage is not present when generating embeds.
This feature seems to be already implemented in Azure OpenAI SDK Implementation:

is this planned to be implemented,  is it possible to use the Azure SDK as a drop-in replacement?

https://github.com/Azure/azure-sdk-for-net/issues/44599

**Comment by joseharriaga** [comment]
Thank you for reaching out, @cosmez ! This feature works the same in this library as it does in the Azure SDK. To get the usage information, you must call the `EmbeddingClient`'s `GenerateEmbeddings` (plural) method. This returns an `EmbeddingCollection`, which has the `Usage` property that you're looking for. This is contrary to the `GenerateEmbedding` (singular) method, which returns a single `Embedding`. The reason why the `Usage` is on the `EmbeddingCollection` and not each individual `Embedding` stems from how the REST API works. You can see in the [OpenAI REST API reference](https://platform.openai.com/docs/api-reference/embeddings/create) that the "usage" property is on the collection. In that sense, the `GenerateEmbeddings` (plural) method is what maps more closely to REST API, but we added the `GenerateEmbedding` (singular) method as a convenience for simpler scenarios. However, based on your question, it's making me wonder if this is generating unnecessary confusion. Would it help if we added a code example specifically illustrating how to retrieve the usage in embedding operations? Or do you think we should consider removing the `GenerateEmbedding` (singular) method? I would love to hear your opinion.

**Comment by cosmez** [comment]
Thanks! i will use that one instead.  i was using an alternative that is actually using the multiple embeddings endpoint :

```csharp
EmbeddingClient client = new(_configuration.EmbeddingModel, _configuration.OpenAiKey);


BinaryData input = BinaryData.FromObjectAsJson(new
{
    model = _configuration.EmbeddingModel,
    input = text,
    encoding_format = "float"
});

using BinaryContent content = BinaryContent.Create(input);
ClientResult result = await client.GenerateEmbeddingsAsync(content);
BinaryData output = result.GetRawResponse().Content;

using JsonDocument outputAsJson = JsonDocument.Parse(output.ToString());
var root = outputAsJson.RootElement;

JsonElement usage = root
    .GetProperty("usage"u8);

int totalTokens = usage.GetProperty("total_tokens"u8).GetInt32();
int promptTokens = usage.GetProperty("prompt_tokens"u8).GetInt32();
```
