### ISSUE TITLE
Fully support the "limit" query parameter in GetMessages and GetMessagesAsync for Assistants

### ISSUE THREAD

**Issue by fribergpg** [openai/openai-dotnet#178]
### Confirm this is not a feature request for the underlying OpenAI API.

- [X] This is not a feature request for the underlying OpenAI API

### Confirm this is not a feature request for Azure OpenAI.

- [X] This is not a feature request for Azure OpenAI

### Describe the feature or improvement you're requesting

Getting messages has support for a limit query parameter (https://platform.openai.com/docs/api-reference/messages/listMessages) but it's not available in the main methods of the GetMessages and GetMessagesAsync. 

An extension method exists for both, with the limit param, but it's implemented a bit strangely and doesn't have the same return type. This should probably be removed.

Ideal usage:

`PageableCollection<ThreadMessage> messages = assistantClient.GetMessages(threadId, limit: 20);`

This should return the 20 newest messages in the active thread.

**Comment by joseharriaga** [comment]
Thank you for reaching out, @fribergpg ! As of version [2.0.0-beta.9](https://www.nuget.org/packages/OpenAI/2.0.0-beta.9), the `AssistantClient`'s `GetMessages` method can take a `MessageCollectionOptions` parameter. `MessageCollectionOptions` has a property called `PageSize`, which is equivalent to the "limit" query parameter that you're referring to. We're considering renaming it (perhaps to something like `PageSizeLimit`) to make it a little more obvious.

**Comment by fribergpg** [comment]
Look at that! Beautiful! Thanks for the quick reply, I'll upgrade to Beta 9! 👍
