### ISSUE TITLE
Is there a way to set stopSequences? I can see the option in the Typescript and Python APIs but not .NET

### ISSUE THREAD

**Issue by sashababayan** [openai/openai-dotnet#211]
### Confirm this is not a feature request for the underlying OpenAI API.

- [X] This is not a feature request for the underlying OpenAI API

### Confirm this is not a feature request for Azure OpenAI.

- [X] This is not a feature request for Azure OpenAI

### Describe the feature or improvement you're requesting

I would like to set stopSequences but it appears to be read only

**Comment by joseharriaga** [comment]
Thank you for reaching out, @sashababayan . `StopSequences` is already initialized. You can add and remove elements directly like this:
```csharp
ChatCompletionOptions options = new();
options.StopSequences.Add("foo");
```

**Comment by sashababayan** [comment]
thanks!
