### ISSUE TITLE
api.md missing

### ISSUE THREAD

**Issue by edisonyls** [openai/openai-dotnet#212]
### Confirm this is not an issue with the OpenAI Python Library

- [X] This is not an issue with the OpenAI Python Library

### Confirm this is not an issue with the underlying OpenAI API

- [X] This is not an issue with the OpenAI API

### Confirm this is not an issue with Azure OpenAI

- [X] This is not an issue with Azure OpenAI

### Describe the bug

I want to see the full description for the APIs but seems like the api.md is not existing.

### To Reproduce

N/A

### OS

macOS

### .NET version

.NET CORE

### Library version

8.0

**Comment by joseharriaga** [comment]
Thank you for reaching out, @edisonyls ! Instead of having a markdown file, we have the following C# file that describes the full API:
🔗 https://github.com/openai/openai-dotnet/blob/main/api/OpenAI.netstandard2.0.cs

**Comment by edisonyls** [comment]
Thanks for the info!
