### ISSUE TITLE
AssistantClient

### ISSUE THREAD

**Issue by mrakowRC** [openai/openai-dotnet#237]
### Service

OpenAI

### Describe the bug

Im trying to use the Assistat and i keep getting this error in the console
Error (active)	OPENAI001	'OpenAI.Assistants.AssistantClient' is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.

### Steps to reproduce

All you have to do is add AssistantClient assistantClient = openAIClient.GetAssistantClient(); to any .cs file in a blazor app

### Code snippets

```C#
OpenAIClient openAIClient = new(Environment.GetEnvironmentVariable("OPENAI_API_KEY"));
OpenAIFileClient fileClient = openAIClient.GetOpenAIFileClient();
AssistantClient assistantClient = openAIClient.GetAssistantClient();
```

### OS

11

### .NET version

.NET 8

### Library version

2.0.0

**Comment by HedgehogNSK** [comment]
Hello,  @mrakowRC. 
I faced with the same error in version 2.1.0.
Bug marked  as complete. Could you please tell me how to properly avoid this error?

**Comment by joseharriaga** [comment]
Hello, @HedgehogNSK! If you're okay with using experimental features, you can acknowledge this by suppressing the warning as described here:
🔗 https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/experimental-overview
