### ISSUE TITLE
FineTuningClient is not fully implemented

### ISSUE THREAD

**Issue by minzdrav** [openai/openai-dotnet#24]
Hi Dev Team
Looks like FineTuningClient is created by some tool and nobody has checked it.
Example:
```c#
public virtual async Task<ClientResult> CreateJobAsync(BinaryContent content, RequestOptions options = null)
``` 
The content type is BinaryContent. The method should accept the base model, training file, etc: https://platform.openai.com/docs/api-reference/fine-tuning/create
Please implement FineTuningClient. Thank you!

**Comment by trrwilson** [comment]
Hello, @minzdrav! Fine-tuning and Batch are currently supported via [protocol methods](https://github.com/openai/openai-dotnet?tab=readme-ov-file#using-protocol-methods), which are "binary in, binary out" overloads available for all operations that are just hidden for ones with strongly typed convenience methods.

For example, to [create a fine-tuning job](https://platform.openai.com/docs/api-reference/fine-tuning/create), you can use:

```csharp
FineTuningClient client = new();

BinaryData request = BinaryData.FromString("""
{
  training_file="file-abc123",
  model="gpt-3.5-turbo"
}
""");
ClientResult protocolResult = await client.CreateJobAsync(BinaryContent.Create(request));

using JsonDocument responseDocument = JsonDocument.Parse(protocolResult.GetRawResponse().Content);
string jobId = responseDocument.RootElement.GetProperty("id").GetString();
```

This direct REST pattern is fully supported for all methods and not an oversight.

We'll be rapidly improving the convenience layer support over the coming weeks, including strongly typed models for Fine Tuning.

**Comment by trrwilson** [comment]
I've opened an issue with tasks to track those remaining convenience surfaces directly: #26 

I'll close this issue to keep that work consolidated and we'll make sure those tasks are updated as the new convenience surfaces become available. Thank you again!
