### ISSUE TITLE
Tool choice serializes erroneously causing error in Realtime API

### ISSUE THREAD

**Issue by jimmystridh** [openai/openai-dotnet#248]
### Service

OpenAI

### Describe the bug

when setting tool choice in the session options of the realtime api in 2.1.0-beta.1 like this:
`conversationSessionOptions.ToolChoice = ConversationToolChoice.CreateNoneToolChoice();`

it doesn't work and the API seems to not like the serialization of the value to pascal case.

`Error: Invalid value: 'None'. Supported values are: 'auto', 'none', and 'required'., Code: invalid_value, Details: session.tool_choice`

### Steps to reproduce

1. set tool choice in the Realtime API session, like
`conversationSessionOptions.ToolChoice = ConversationToolChoice.CreateNoneToolChoice();`
2. listen to events
3. start a new session
4. observe error event being reported back

### OS

MacOS

### .NET version

8

### Library version

2.1.0-beta.1

**Comment by raimondasl** [comment]
I have the same issue. Is this going to be fixed? Is there a workaround to set ToolChoice in dotnet?

**Comment by joseharriaga** [comment]
Thank you for reaching out, @jimmystridh ! This has been fixed in version 2.1.0-beta.2, which was released yesterday.
