### ISSUE TITLE
GenerateImageEdit not working

### ISSUE THREAD

**Issue by Fableton** [openai/openai-dotnet#250]
### Service

OpenAI

### Describe the bug

GenerateImageEdit is not working and force you to use "dall-e-2"

### Steps to reproduce

Send any image to function

### Code snippets

```C#
//Retunr the same image.
ClientResult<GeneratedImage> response = imageClient.GenerateImageEdit(imagePath, prompt);
```

### OS

windows

### .NET version

core 8

### Library version

2.0

**Comment by joseharriaga** [comment]
Thank you for reaching out, @Fableton ! Generating edited images is currently only supported by the DALL-E-2 model as per the documentation here: 
🔗 https://platform.openai.com/docs/api-reference/images/createEdit
