### ISSUE TITLE
AzureExtensionsOptions and AzureExtensionsContext are gone after upgrading to stable version of the library

### ISSUE THREAD

**Issue by i02coroj** [openai/openai-dotnet#257]
### Service

Azure OpenAI

### Describe the bug

With the prerelease version I used to use `AzureExtensionsOptions` inside `ChatCompletionsOptions` to set my Azure AI Search configuration.
Then, in the response after making the call I used to use `message.AzureExtensionsContext.Citations`.

After upgrading to latest stable version of Azure.AI.OpenAI library all those options are gone.
I cannot find any details about it but it seems to me like a breaking change?

Any help with it, please? Maybe there's a different way to do it now.
Cheers.

### Steps to reproduce

1. Upgrade Azure.AI.OpenAI from 2.0.0-beta.1 to 2.0.0.
2. Try to use this piece of code:
![image](https://github.com/user-attachments/assets/85d74b8b-3469-4e6a-afed-6ad2ae37066b)

### Code snippets

```C#
var chatCompletionsOptions = new ChatCompletionsOptions
        {            
            AzureExtensionsOptions = new AzureChatExtensionsOptions()
            {
                Extensions =
                {
                    new AzureSearchChatExtensionConfiguration()
                    {
                        SearchEndpoint = new Uri(_searchSettings.SearchUri),
                        Authentication = new OnYourDataApiKeyAuthenticationOptions(searchKey),
                        IndexName = _indexName,
                        QueryType = AzureSearchQueryType.Semantic,
                        SemanticConfiguration = $"{_indexName}-semantic-config"
                    },
                },
            }
        };

...

var citations = message.AzureExtensionsContext.Citations;
```

### OS

Windows 11

### .NET version

8

### Library version

2.0.0

**Comment by KrzysztofCwalina** [comment]
I think you can do:
```csharp
var chatCompletionsOptions = new ChatCompletionsOptions();
chatCompletionsOptions.AddDataSource(new AzureSearchChatDataSource() { ... });
```

**Comment by KrzysztofCwalina** [comment]
I am glad it helped. Yeah, sorry for the docs not yet being great. They will get better over time.
