### ISSUE TITLE
Add typed support for `store` boolean on chat completion

### ISSUE THREAD

**Issue by connellPortrait** [openai/openai-dotnet#271]
### Confirm this is a feature request for the .NET library and not the underlying OpenAI API

- [X] This is a feature request for the .NET library

### Describe the feature or improvement you are requesting

Hello, I'd like to request adding the `store` param to the ChatCompletionOptions 
https://platform.openai.com/docs/api-reference/chat/create?lang=python

**Comment by sscowden** [comment]
Between this and being able to see cached token usage, I'm regretting moving from my own REST requests to this package. If it lags months behind new features, the viability of the whole package is greatly reduced.

**Comment by joseharriaga** [comment]
Thank you for reaching out, @connellPortrait ! Support for storing the output of chat completions is available as of version 2.1.0-beta.2.

@sscowden : Support for cached token usage is also available as of version 2.1.0-beta.2.

**Comment by sscowden** [comment]
> Thank you for reaching out, @connellPortrait ! Support for storing the output of chat completions is available as of version 2.1.0-beta.2.
> 
> @sscowden : Support for cached token usage is also available as of version 2.1.0-beta.2.

Thanks for the tag! Will give it a try today.
