### ISSUE TITLE
`parallel_tool_calls` is missing from generated code

### ISSUE THREAD

**Issue by algunion** [openai/openai-dotnet#31]
The `parallel_tool_calls` parameter is included in the official documentation and the specification [file](https://github.com/openai/openai-openapi/blob/master/openapi.yaml).

However, the code generation seems to omit this parameter altogether.

Since the parameter is set to `true` by default, specific scenarios are less predictable when using function tool calling (e.g., even if only one tool is present, the output can result in the same tool call being repeated with different parameters - which is not always desirable).

**Comment by trrwilson** [comment]
Thank you, @algunion!

You're quite correct, and it'll be added soon. The input specification for the initial preview release was frozen to [d376fedb](https://github.com/openai/openai-openapi/commit/d376fedb9068e09c225eac1f18401613efcef9d0) to fully validate stability -- prior to the changes last week -- and that means `parallel_tool_calls` and `chunking_strategy` for vector stores aren't yet represented.

We're working to reduce this latency to as near to simultaneous with the spec as possible and will continue to rapidly update.
