### ISSUE TITLE
Should OpenAIModelFactory be public?

### ISSUE THREAD

**Issue by Blackbaud-TimMcVicker** [openai/openai-dotnet#46]
In the initial Azure.Ai.OpenAi versions of this library, we could use AzureOpenAIModelFactory to create objects to use in our mocks, per this issue  https://github.com/Azure/azure-sdk-for-net/issues/36462. This was useful when writing tests that mocked out the OpenAIClient.

The [new version](https://github.com/openai/openai-dotnet/blob/e6fe89c6e635840ffd0682b118983392b22d756d/src/Generated/OpenAIModelFactory.cs#L18) of that seems to be marked internal instead of public. Is that intentional? If so, what should we be using to create those objects in our mocks?

**Comment by KrzysztofCwalina** [comment]
We will be adding an official way to create models for mocking, but for now you can use the following workaround:

```csharp
        ChatCompletion completion = ModelReaderWriter.Read<ChatCompletion>(BinaryData.FromObjectAsJson(new {
            id = "1234",
            choices = new object[]
            {
                new {
                    finish_reason = "stop",
                    index = 0,
                    message = new {
                        content = "It's a nice day today!",
                        role = "assistant"
                    }
                }
            },
            created = DateTimeOffset.Now.ToUnixTimeSeconds(),
            model = "model",
            system_fingerprint = "N/A",
            @object = "N/A",
            usage = (object)null
        }));
```

**Comment by joseharriaga** [comment]
I have created the following issue to track the work needed to add support for mocking: 🔗 https://github.com/openai/openai-dotnet/issues/121

I will close the present issue so that we can follow up in one single place. 😊 Thank you, @Blackbaud-TimMcVicker !
