### ISSUE TITLE
Is it possible to allow changes to the `encoding_format` of the embedded options?

### ISSUE THREAD

**Issue by JadynWong** [openai/openai-dotnet#51]
Currently `EmbeddingClient` fixes the `encoding_format` value to base64 for better performance.

https://github.com/openai/openai-dotnet/blob/45fc4d72c12314aea83264ebe2e1dc18870e5c06/src/Custom/Embeddings/EmbeddingGenerationOptions.cs#L77-L82

https://github.com/openai/openai-dotnet/blob/45fc4d72c12314aea83264ebe2e1dc18870e5c06/src/Custom/Embeddings/Embedding.cs#L75-L84

It can't be changed, even if I want to use float format. I want to use this client for [text-embeddings-inference](https://github.com/huggingface/text-embeddings-inference), which currently does not support the `encoding_format` parameter.
This results in the following error

```
The input is not a valid Base64 string of encoded floats.
```

 I know that `encoding_format` compatibility would be a better approach in other projects, but a lot of compatible openai api's don't update as fast as they should.

Is it possible to allow users to change the `encoding_format` value? 
Of course, as the official SDK of OpenAI, I would respect it if it was only compatible with OpenAI.

For now I can serialize it myself using protocol methods.

**Comment by joseharriaga** [comment]
Thank you for reaching out, @JadynWong ! Presently, it is not in our plans to expose the `encoding_format` property publicly, but we will definitely take your feedback into consideration as we continue to evolve this API.

As you have correctly pointed out, you can use the `EmbeddingClient`'s `GenerateEmbeddings` protocol method to have full control of the request that is sent to the OpenAI service. By the sound of it, you have it all figured out already, but I am including a small example below in case others might find it useful:

```csharp
EmbeddingClient client = new("text-embedding-3-small", Environment.GetEnvironmentVariable("OPENAI_API_KEY"));

string description = "Best hotel in town if you like luxury hotels. They have an amazing infinity pool, a spa,"
    + " and a really helpful concierge. The location is perfect -- right downtown, close to all the tourist"
    + " attractions. We highly recommend this hotel.";

BinaryData input = BinaryData.FromObjectAsJson(new
{
    model = "text-embedding-3-small",
    input = description,
    encoding_format = "float"
});

using BinaryContent content = BinaryContent.Create(input);
ClientResult result = await client.GenerateEmbeddingsAsync(content);
BinaryData output = result.GetRawResponse().Content;

using JsonDocument outputAsJson = JsonDocument.Parse(output.ToString());
JsonElement vector = outputAsJson.RootElement
    .GetProperty("data"u8)[0]
    .GetProperty("embedding"u8);

Console.WriteLine($"Dimension: {vector.GetArrayLength()}");
Console.WriteLine($"Floats: ");
int i = 0;
foreach (JsonElement element in vector.EnumerateArray())
{
    Console.WriteLine($"  [{i++,4}] = {element.GetDouble()}");
}
```

Note that, when using protocol methods, the input and output (represented as `BinarayData`) map directly to the REST API as described here: 🔗 https://platform.openai.com/docs/api-reference/embeddings/create

I have also created the following PR to add this example to our suite: 🔗 https://github.com/openai/openai-dotnet/pull/122
