### ISSUE TITLE
detailed Content filter info

### ISSUE THREAD

**Issue by wolfgangschneider** [openai/openai-dotnet#55]
When completion is cancelnd in case of contentfilter Version one throes an Azure.RequestFailedException with detailed information as Json stored in Content:

```
_Azure.RequestFailedException: The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766
Status: 400 (model_error)
ErrorCode: content_filter


Content:
{"error":{"message":"The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766","type":null,"param":"prompt","code":"content_filter","status":400,"innererror":

{"code":"ResponsibleAIPolicyViolation","content_filter_result":{"hate":{"filtered":false,"severity":"safe"},"self_harm":

{"filtered":false,"severity":"safe"},"sexual":{"filtered":true,"severity":"high"},"violence":{"filtered":false,"severity":"safe"}}}}}_
```

Version 2 throws System.ClientModel.ClientResultException without this information

```
_System.ClientModel.ClientResultException: HTTP 400 (content_filter)
Parameter: prompt

The response was filtered due to the prompt triggering Azure OpenAI's content management policy. 
Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766_

```

Is it possible to get the Content filter reason in one or an other way?

**Comment by joseharriaga** [comment]
Hello, @wolfgangschneider. Thank you for reaching out! This repo is for the official OpenAI library for .NET. If you're working with Azure OpenAI and using the [Azure.AI.OpenAI](https://www.nuget.org/packages/Azure.AI.OpenAI) library, please open an issue in the [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net/issues) repo instead.

**Comment by wolfgangschneider** [comment]
I will do so

**Comment by ZaneBartlett1** [comment]
Just because this has good SEO and is currently the top result when searching this problem for me, I couldn't find any ticket in the azure-sdk-for-net that was being linked to, so I opened an issue: https://github.com/Azure/azure-sdk-for-net/issues/48145

If anyone is having the same problem, I'd upvote that issue!
