### ISSUE TITLE
[Tracking] On .NET Framework (net481), request URIs can contain a malformed double question mark (`??`) for operations with query string parameters

### ISSUE THREAD

**Issue by trrwilson** [openai/openai-dotnet#57]
Note: this is benign for direct use of the OpenAI v1 endpoint, as the service ignores the extra `?`; the impact of this behavior is limited to alternative destinations (like intermediate API gateways or proxies) that may not be as permissive.

This problem is addressed in the generator by the following and this issue can be resolved as soon as the change is integrated:
https://github.com/Azure/autorest.csharp/pull/4818

**Comment by joseharriaga** [comment]
The following PR addresses this issue: 🔗 https://github.com/openai/openai-dotnet/pull/120
