### ISSUE TITLE
GetRunStepsAsync does not yet take a CancellationToken parameter

### ISSUE THREAD

**Issue by dspear** [openai/openai-dotnet#61]
I just got the latest NuGet package and I love all the new CancellationToken parameters. GetRunStepsAsync is one of the calls I make where it is missing.

**Comment by KrzysztofCwalina** [comment]
I see the following overload of GetRunStepsAsync that does take a cancellation token:
```public virtual AsyncPageableCollection<RunStep> GetRunStepsAsync(string threadId, string runId, ListOrder? resultOrder = null, CancellationToken cancellationToken = default);```

**Comment by dspear** [comment]
You're absolutely right. I don't know why that didn't seem to show up a few days ago. Thanks, issue resolved, sorry to trouble you.

**Comment by trrwilson** [comment]
The protocol methods (the ones that take `RequestOptions` and provide a binary, non-generic `ClientResult` return value) for `AssistantClient` appear to currently lack the intended `[EditorBrowsable(EditorBrowsableState.Never)]` attribute, which almost certainly made it a lot easier to miss the intended overloads. I'll correct that.

**Comment by KrzysztofCwalina** [comment]
> You're absolutely right. I don't know why that didn't seem to show up a few days ago. Thanks, issue resolved, sorry to trouble you.

@dspear, not problem. no need to appologize. thanks for trying the beta and we are looking forward to any future feedback you have.
