### ISSUE TITLE
When I upload a file with a Chinese txt format or other format in the file name, it prompts that the uploaded file does not support it

### ISSUE THREAD

**Issue by LinzhouWang1** [openai/openai-dotnet#72]
When I upload a file with a Chinese txt format or other format in the file name, it prompts that the uploaded file does not support it
<img width="558" alt="企业微信截图_17187767209882" src="https://github.com/openai/openai-dotnet/assets/155417580/3d251fc2-c0b9-4de9-a5c9-6400bce59a43">
<img width="757" alt="企业微信截图_17187768056251" src="https://github.com/openai/openai-dotnet/assets/155417580/e67fc9da-6fda-4229-9db7-5ca1723f4300">

**Comment by LinzhouWang1** [comment]
step1:
![image](https://github.com/openai/openai-dotnet/assets/155417580/c2553b92-5e17-4c24-a972-96869b8f4130)

step2:
![image](https://github.com/openai/openai-dotnet/assets/155417580/c2fb9585-a09d-478c-8da8-1fafd00c29f2)

step3:

<img width="757" alt="企业微信截图_17187768056251" src="https://github.com/openai/openai-dotnet/assets/155417580/27681fab-51bd-4567-88c5-a3de1a4b9def">

**Comment by trrwilson** [comment]
Thank you for reporting this problem, @LinzhouWang1! This is a problem with the SDK's encoding of `filename` in `multipart/form-data` `Content-Disposition` -- we're following up and will get this fixed ASAP.
