### ISSUE TITLE
Is it possible to use a Proxy-Server?

### ISSUE THREAD

**Issue by aurora** [openai/openai-dotnet#74]
I wonder if there is an easy way to use a proxy server for connecting to the API. In Azure.AI.OpenAI, it is possible via HttpClientTransport in Azure.Core.Pipeline, and other libraries (such as Semantic Kernel) allow specifying a custom HttpClient instance. But I can't find a way to use a similar method with this library.

**Comment by trrwilson** [comment]
Hello, @aurora!

`System.ClientModel` has a very similar pipeline concept and you can supply a custom `HttpClient`/transport via the client options instance:

```csharp
OpenAIClientOptions options = new()
{
    Transport = new HttpClientPipelineTransport(myHttpClient),
};
OpenAIClient client = new(options);
```

**Comment by aurora** [comment]
Hi @trrwilson,

Oh, I somehow overlooked this option. It works perfectly. Many thanks for your quick reply and help!
