### ISSUE TITLE
Assistant with Multiple Vector Store Ids?

### ISSUE THREAD

**Issue by hemnaathR** [openai/openai-dotnet#78]
Hello,
I noticed that when creating the Assistant you could pass in a list of VectorStoreIds? At the moment however we can only pass in one VectorStoreId per Assistant. Does that mean there are plans for an Assistant to use multiple Vector Stores in the future?

```
Assistant assistant = await assistantClient.CreateAssistantAsync(
    model: "gpt-4",
    new AssistantCreationOptions()
    {
        Name = "Assistant v2",
        Tools =
                {
                    new FileSearchToolDefinition(),
                },
        ToolResources = new()
        {
            FileSearch = new()
            {
                VectorStoreIds = [vs1.Id] // can support multiple ids in the future?
            }
        },
    });
```

**Comment by trrwilson** [comment]
Great question, @hemnaathR! With the disclaimer that I have no insider knowledge one way or another, I'll say that guess makes a lot of sense to me and that I share it -- there wouldn't be much of a reason to define this as an "array of one item" (per [API reference](https://platform.openai.com/docs/api-reference/assistants/createAssistant#assistants-createassistant-tool_resources) and [YAML spec](https://github.com/openai/openai-openapi/blob/0f5de60a3d2b263dc2ac362371673f7a21811874/openapi.yaml#L10029) if there weren't a prediction of having more than one.

**Comment by hemnaathR** [comment]
Cool. Fingers crossed. 🤞🏼
