### ISSUE TITLE
Parsing the OpenAI messages json

### ISSUE THREAD

**Issue by slreznit** [openai/openai-dotnet#99]
Hi,

I would like to use this SDK to Parse the messages Json and then iterate it and access the different fields

For example, can I do this?

```
 var messages = """
     [
         {
               "role": "system",
               "content": "You are an AI assistant..."
         },
         {
               "role": "user",
               "content": "some user question",
         }
     ]
     """;
```

```
List<ChatMessage> p = ParseChatRequest(messages);
foreach (var message in p)
{
    Print($"{p.role}, {p.content}").
}
```

**Comment by sunnynagavo** [comment]
```
public class ChatMessage
{
    public string Role { get; set; }
    public string Content { get; set; }
}

static List<ChatMessage> ParseChatRequest(string json)
{
    return JsonSerializer.Deserialize<List<ChatMessage>>(json);
}
```
you can simply do this right ?

**Comment by joseharriaga** [comment]
Thank you for reaching out, @slreznit ! I have an open PR to add an example that illustrates how to serialize/deserialize a list of messages:
🔗 https://github.com/openai/openai-dotnet/pull/124

Specifically, this file:
🔗 https://github.com/openai/openai-dotnet/pull/124/files#diff-5813b799855b3942f5ae2dac0014c17b8fa0088683506455676d656ef359cf7a

I would also like to add that we're working on making this simpler in the future. 😊

**Comment by omri08** [comment]
Hello @joseharriaga,
Can you also share an example on how to serialize / deserialize messages that has `input_audio` ?

**Comment by joseharriaga** [comment]
Hello, @omri08! We're preparing a fix for this issue, and our current estimate is to release it next week. Please stay tuned. 🙂

**Comment by omri08** [comment]
You are the best  🙂
